name: Node.js CI

on: 
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main, dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn
      - run: yarn build
      - run: yarn test
