name: Node.js CI

on: [push]

jobs:
  lint-format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn
      - run: yarn format
      - run: yarn lint
